jasypt:
  encryptor:
    # 加密使用的 salt
    # password: As12mda-02mdAadi123df
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
server:
  port: 8022
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: ENC(lDEBjN01BigteIWrpKA6ew==)
    password: ENC(f3kS535Eu8fhA/jVvTgxx4xDVS7uAtuP)